### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by eddy-kwok** [alexsasharegan/vue-flex#2] opened 2019-08-07 09:53 UTC
vueflex.js:13 Uncaught TypeError: _node_modules_vue_flex__WEBPACK_IMPORTED_MODULE_1__.default is not a constructor
    at eval (vueflex.js:13)
    at Module../src/vueflex.js (app.js:8270)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (main.js:260)
    at Module../src/main.js (app.js:8186)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at Object.1 (app.js:8284)
    at __webpack_require__ (app.js:767)

**Comment by alexsasharegan** [comment] 2019-08-07 12:27
Hi, my name is Alex. I can’t solve your stack trace. If you would like to provide an explanation to what’s going on, I might be able to provide you assistance. For example, you might want to provide code snippets of how you are using vue-flex.

**Comment by eddy-kwok** [comment] 2019-08-07 15:55
Hi Alex,

In my project folder,
run npm i vue-flex

create vueflex.js file and copy all the content suggested in your doco,
insert path ../npm_modules/

 in main.js import the file

run. npm run serve

When opening the app in browser, nothing displayed,  it's throw out error
in browser console,

I haven't use your code yet...

**Comment by alexsasharegan** [comment] 2019-08-07 15:57
Can you paste in the actual content of this vueflex.js file? I can't provide accurate help without a true representation of the code. Also, how are you intending to use the library? With modules and webpack? As a script tag include?

**Comment by eddy-kwok** [comment] 2019-08-07 16:10
src/vueflex.js

```js
import Vue from "vue";
// imports the ESM module by default
import VueFlex from "../node_modules/vue-flex";
// Already autoprefixed for vendor prefixes.
// Also namespaced to avoid collisions.
import "../node_modules/vue-flex/dist/vue-flex.css";

Vue.use(VueFlex);
export default new VueFlex();
```

src/main.js
```js
import VueFlex from "./vueflex";

Vue.config.productionTip = false;
new Vue({
router,
store,
axios,
VueFlex,
render: h => h(App)
}).$mount("#app");
```

not sure what do you mean  for the last question...
i use vue-cli webpack, will insert vue-flex code in view or component files.

thanks

**Comment by alexsasharegan** [comment] 2019-08-07 16:19
Some problems with your code (that also do not follow the instructions)

1. Don't import from explicit node modules paths. Use the node resolutions and change to using: `import VueFlex from 'vue-flex` as well as the css `import "vue-flex/dist/vue-flex.css";`
1. You are not using the component correctly. Nowhere in the docs does it tell you to instantiate the `VueFlex` import object. Remove the `export default new VueFlex()`. This is the source of you original error.
1. Remove VueFlex from your root vue object. Nowhere in the docs does it suggest doing this.

Using vue-cli webpack means you're using webpack, and the usage of `export` keywords means you are using modules. This information is important because it means we need to focus on your `import` syntax and import paths.

**Comment by alexsasharegan** [comment] 2019-08-07 16:20
I'm also going to close this issue because it's a usage problem, not a bug. We can continue the conversation to hopefully help you get things working.

**Closed as completed by alexsasharegan** 2019-08-07 16:20 UTC
Labels: question
